language: node_js
node_js:
  - '10'
cache: npm
before_install:
  - openssl aes-256-cbc -K $encrypted_b0dac10bf13a_key -iv $encrypted_b0dac10bf13a_iv
    -in credentials.json.enc -out credentials.json -d
script:
  - npm test
  - npm run build
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: credentials.json
  project: codettastone-website
  default: true
  local_dir: build
  on:
    branch: master
  notifications:
    slack: codettastone:qScIuKQn3aJNCocHf4S8P8G8
